const MAX_STACK_BYTESLICE_LENGTH = 4096;
const ARRAY_PREFIX_LENGTH = 2;
const UINT8_LENGTH = 1;
const UINT16_LENGTH = 2;
const UINT32_LENGTH = 4;
const UINT64_LENGTH = 8;
const UINT128_LENGTH = 16;
const BIGUINT_LENGTH = 64;

export const RESIDUAL_STACK_ARRAY_LENGTH = MAX_STACK_BYTESLICE_LENGTH - ARRAY_PREFIX_LENGTH;
export const MAX_UINT8_IN_STACK_ARRAY = RESIDUAL_STACK_ARRAY_LENGTH / UINT8_LENGTH;
export const MAX_UINT16_IN_STACK_ARRAY = RESIDUAL_STACK_ARRAY_LENGTH / UINT16_LENGTH;
export const MAX_UINT32_IN_STACK_ARRAY = RESIDUAL_STACK_ARRAY_LENGTH / UINT32_LENGTH;
export const MAX_UINT64_IN_STACK_ARRAY = RESIDUAL_STACK_ARRAY_LENGTH / UINT64_LENGTH;
export const MAX_UINT128_IN_STACK_ARRAY = RESIDUAL_STACK_ARRAY_LENGTH / UINT128_LENGTH;
export const MAX_BIGUINT_IN_STACK_ARRAY = RESIDUAL_STACK_ARRAY_LENGTH / BIGUINT_LENGTH;
