[algokit]
min_version = "v1.12.1"

[project]
type = 'workspace'
projects_root_path = 'projects'

[generate.devcontainer]
description = "Generate a default 'devcontainer.json' configuration that pre-installs algokit and launches Algorand sandbox as part of codespace container provisioning."
path = ".algokit/generators/create-devcontainer"

# FIXME: remove explicit order of subprojects when the related PR is merged.
# AlgoKit CLI "algokit project run <name>" will execute all subproject's scripts that match <name> concurrently.
# This is a problem for <name> == ci-teal-diff because they all try to acquire the git lock for that repo concurrently
#  and inevitably fail when not all are able to do so at the same time.
# This PR will introduce a flag that allows the CLI to execute scripts sequentially.
# https://github.com/algorandfoundation/algokit-cli/pull/557
[project.run]
ci-teal-diff = ['lib-pcg-algopy', 'lib-pcg-ts', 'lib-pcg-pyteal', 'unified_tests']
