[algokit]
min_version = "v2.0.0"

[project]
# This is supposed to be 'contract' but that does not allow linking. 'frontend' type does.
type = 'frontend'
name = 'unified-tests'
artifacts = 'smart_contracts/artifacts'

[project.run]
# Commands intented for use locally and in CI
test-algopy = { commands = [
  'poetry run pytest --language=algopy'
], description = 'Run lib-pcg algopy implementation tests' }
test-algots = { commands = [
  'poetry run pytest --language=algots'
], description = 'Run lib-pcg ts implementation tests' }
test-pyteal = { commands = [
  'poetry run pytest --language=pyteal'
], description = 'Run lib-pcg pyteal implementation tests' }
test = { commands = [
  'algokit project run test-algopy',
  'algokit project run test-algots',
  'algokit project run test-pyteal',
], description = 'Run smart contract tests' }
audit = { commands = [
  'poetry run pip-audit',
], description = 'Audit with pip-audit. NOTE: If used with poetry >v2, make sure to install `poetry-plugin-export` as per https://github.com/python-poetry/poetry-plugin-export#installation.' }
lint = { commands = [
  'poetry run black .',
  'poetry run ruff check . --fix',
], description = 'Perform linting' }

# Commands intented for CI only, prefixed with `ci-` by convention
ci-teal-diff = { commands = [
  'git add -N ./smart_contracts/artifacts',
  'git diff --exit-code --minimal ./smart_contracts/artifacts',
], description = 'Check TEAL files for differences' }
ci-lint = { commands = [
  'poetry run black --check --diff .',
  'poetry run ruff check .',
  'poetry run mypy',
], description = 'Perform linting' }
