[algokit]
min_version = "v2.0.0"

[generate.smart_contract]
description = "Adds new smart contract to existing project"
path = ".algokit/generators/create_contract"

[project]
type = 'contract'
name = 'lib-pcg-pyteal'
artifacts = 'smart_contracts/artifacts'

[project.deploy]
command = "poetry run python -m smart_contracts deploy"
environment_secrets = [
  "DEPLOYER_MNEMONIC",
  "DISPENSER_MNEMONIC",
]

[project.deploy.localnet]
environment_secrets = []

[project.run]
# Commands intented for use locally and in CI
build = { commands = [
  'poetry run python -m smart_contracts build',
], description = 'Build all smart contracts in the project' }
audit = { commands = [
  # Since beaker is deprecated and relies on algokit-utils <3.0.0, we can't easily upgrade algokit-utils
  #  and therefore resolve GHSA-vqfr-h8mv-ghfj.
  'poetry run pip-audit --ignore-vuln GHSA-vqfr-h8mv-ghfj',
], description = 'Audit with pip-audit' }
audit-teal = { commands = [
  # 🚨 IMPORTANT 🚨: For strict TEAL validation, remove --exclude statements. The default starter contract is not for production. Ensure thorough testing and adherence to best practices in smart contract development. This is not a replacement for a professional audit.
  'algokit task analyze smart_contracts/artifacts --recursive --force --exclude rekey-to --exclude is-updatable --exclude missing-fee-check --exclude is-deletable --exclude can-close-asset --exclude can-close-account --exclude unprotected-deletable --exclude unprotected-updatable',
], description = 'Audit TEAL files' }
lint = { commands = [
  'poetry run black .',
  'poetry run ruff check . --fix',
], description = 'Perform linting' }

# Commands indented for CI only, prefixed with `ci-` by convention
ci-teal-diff = { commands = [
  'git add -N ./smart_contracts/artifacts',
  'git diff --exit-code --minimal ./smart_contracts/artifacts',
], description = 'Check TEAL files for differences' }
ci-lint = { commands = [
  'poetry run black --check --diff .',
  'poetry run ruff check .',
  'poetry run mypy',
], description = 'Perform linting' }
