# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.5.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: giorgio.ciotti@algorand.foundation
author_name: CiottiGiorgio
contract_name: hello_world
deployment_language: python
preset_name: production
project_name: unified-tests

