[algokit]
min_version = "v2.0.0"

[project]
type = 'frontend'
name = 'common_tests'
artifacts = 'smart_contracts/artifacts'

[project.run]
test-algopy = { commands = [
  'poetry run pytest --language=algopy'
], description = 'Run lib-pcg algopy implementation tests'}
test-pyteal = { commands = [
  'poetry run pytest --language=pyteal'
], description = 'Run lib-pcg pyteal implementation tests'}
test-ts = { commands = [
  'poetry run pytest --language=ts'
], description = 'Run lib-pcg ts implementation tests'}
test = { commands = [
  'algokit project run test-algopy',
  'algokit project run test-pyteal',
  'algokit project run test-ts'
], description = 'Run smart contract tests' }
audit = { commands = [
  'poetry export --without=dev -o requirements.txt',
  'poetry run pip-audit -r requirements.txt',
], description = 'Audit with pip-audit' }
lint = { commands = [
  'poetry run black .',
  'poetry run ruff . --fix',
], description = 'Perform linting' }
lint-check = { commands = [
  'poetry run black --check .',
  'poetry run ruff .',
  'poetry run mypy',
], description = 'Perform linting checks' }
