MAX_STACK_BYTESLICE_LENGTH = 4096
ARRAY_PREFIX_LENGTH = 2
UINT8_LENGTH = 1
UINT16_LENGTH = 2
UINT32_LENGTH = 4
UINT64_LENGTH = 8
UINT128_LENGTH = 16
BIGUINT_LENGTH = 64

RESIDUAL_STACK_ARRAY_LENGTH = MAX_STACK_BYTESLICE_LENGTH - ARRAY_PREFIX_LENGTH
MAX_UINT8_IN_STACK_ARRAY = RESIDUAL_STACK_ARRAY_LENGTH // UINT8_LENGTH
MAX_UINT16_IN_STACK_ARRAY = RESIDUAL_STACK_ARRAY_LENGTH // UINT16_LENGTH
MAX_UINT32_IN_STACK_ARRAY = RESIDUAL_STACK_ARRAY_LENGTH // UINT32_LENGTH
MAX_UINT64_IN_STACK_ARRAY = RESIDUAL_STACK_ARRAY_LENGTH // UINT64_LENGTH
MAX_UINT128_IN_STACK_ARRAY = RESIDUAL_STACK_ARRAY_LENGTH // UINT128_LENGTH
MAX_BIGUINT_IN_STACK_ARRAY = RESIDUAL_STACK_ARRAY_LENGTH // BIGUINT_LENGTH
