name: Pull Request CI
on:
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      algopy: ${{ steps.changes.outputs.algopy }}
      algots: ${{ steps.changes.outputs.algots }}
      pyteal: ${{ steps.changes.outputs.pyteal }}
      ts: ${{ steps.changes.outputs.ts }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            algopy:
              - '!(projects/lib-pcg-algots/**)'
              - '!(projects/lib-pcg-pyteal/**)'
              - '!(projects/lib-pcg-ts/**)'
            algots:
              - '!(projects/lib-pcg-algopy/**)'
              - '!(projects/lib-pcg-pyteal/**)'
              - '!(projects/lib-pcg-ts/**)'
            pyteal:
              - '!(projects/lib-pcg-algopy/**)'
              - '!(projects/lib-pcg-algots/**)'
              - '!(projects/lib-pcg-ts/**)'
            ts:
              - '!(projects/lib-pcg-algopy/**)'
              - '!(projects/lib-pcg-algots/**)'
              - '!(projects/lib-pcg-pyteal/**)'

  # We would like to only run each job in case something changes in the respective project.
  # However, we don't want to accidentally miss important changes in workflow, tests, etc. files so
  #  we will specifically ignore changes in other subprojects instead of everything outside the relevant project.
  lib-pcg-algopy-ci-validation:
    name: Run lib-pcg-algopy validation
    needs: changes
    if: needs.changes.outputs.algopy == 'true'
    uses: ./.github/workflows/reusable/algopy-validate.yml

  lib-pcg-algots-ci-validation:
    name: Run lib-pcg-algots validation
    needs: changes
    if: needs.changes.outputs.algots == 'true'
    uses: ./.github/workflows/reusable/algots-validate.yml

  lib-pcg-pyteal-ci-validation:
    name: Run lib-pcg-pyteal validation
    needs: changes
    if: needs.changes.outputs.pyteal == 'true'
    uses: ./.github/workflows/reusable/pyteal-validate.yml

  lib-pcg-ts-ci-validation:
    name: Run lib-pcg-ts validation
    needs: changes
    if: needs.changes.outputs.ts == 'true'
    uses: ./.github/workflows/reusable/ts-validate.yml
