[algokit]
min_version = "v2.0.0"

[project]
type = 'contract'
name = 'lib-pcg-ts'
artifacts = 'contracts/artifacts'

[project.run]
build = { commands = [
  'npm run compile-contract',
], description = 'Build all smart contracts in the project' }
audit = { commands = [
  'npm run audit',
], description = 'Audit with better-npm-audit' }
lint = { commands = [
  'npm run lint:fix',
], description = 'Perform linting' }


# Commands intented for CI only, prefixed with `ci-` by convention
ci-teal-diff = { commands = [
  'git add -N ./contracts/artifacts',
  'git diff --exit-code --minimal ./contracts/artifacts',
], description = 'Check TEAL files for differences' }
ci-lint = { commands = [
  'npm run lint'
], description = 'Perform linting' }
