[algokit]
min_version = "v2.0.0"

[project]
type = 'contract'
name = 'lib-pcg-ts'
artifacts = 'contracts/artifacts'

[project.run]
build = { commands = [ 
  'npm run build',
], description = 'Build all smart contracts in the project' }
lint-check = { commands = [
  'npm run lint',
], description = 'Perform linting checks' }
lint = { commands = [
  'npm run fix',
], description = 'Perform linting' }
